apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: workshop-docs
  namespace: workshop-docs
  labels:
    app: workshop-docs
    workshop: self-healing
    app.kubernetes.io/part-of: self-healing-workshop
spec:
  lookupPolicy:
    local: false
