apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: workshop-docs

resources:
  - namespace.yaml
  - configmap.yaml
  - imagestream.yaml
  - buildconfig.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

labels:
  - pairs:
      workshop: self-healing
      app.kubernetes.io/part-of: self-healing-workshop
